### ISSUE TITLE
Missing dependencies of project Ormlite-Core

### ISSUE THREAD

**Issue by Gu-Youngfeng** [Gu-Youngfeng/EffciencyMinner#6]
Missing dependency libraries of project `Ormlite-Core`, which result in compiling errors in maven building. For example, you will get following errors while running class `Timer`,

```c
Exception in thread "main" spoon.compiler.ModelBuildingException: The import javax.persistence cannot
be resolved at ...\EffciencyMinner\src\main\resources\projs\ormlite_parent\...\JavaxPersistenceImpl.java:6
  at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.report(JDTBasedSpoonCompiler.java:582)
  at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.reportProblems(JDTBasedSpoonCompiler.java:563)
  at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:118)
  at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:99)
  at spoon.Launcher.buildModel(Launcher.java:720)
  at cn.edu.whu.cstar.timer.SRCAnalyzer.getAllClassUnderDir(SRCAnalyzer.java:48)
  at cn.edu.whu.cstar.timer.SRCAnalyzer.<init>(SRCAnalyzer.java:22)
  at cn.edu.whu.cstar.timer.RepsUtilier.getFeatures(RepsUtilier.java:41)
  at cn.edu.whu.cstar.timer.Timer.analyzing(Timer.java:60)
  at cn.edu.whu.cstar.timer.Timer.main(Timer.java:13)
```

**Comment by Gu-Youngfeng** [comment]
All the 7 projects are built with **Maven**, and we then use **maven-assembly-plugin** to package each project into XXX.jar. 

```xml
<!-- maven assembly plugin in pom.xml -->
<plugin>
  <artifactId>maven-assembly-plugin</artifactId>
  <executions>
    <execution>
      <id>make-assembly</id>
      <phase>package</phase>
      <goals>
        <goal>single</goal>
      </goals>
    </execution>
  </executions>
  <configuration>
    <descriptorRefs>
      <descriptorRef>jar-with-dependencies</descriptorRef>
    </descriptorRefs>
  </configuration>
</plugin>
```

But `Ormlite-Core` cannot package with dependencies by command `mvn assembly:single`. We the considered following solutions, but all failed.

- [Including dependencies in a jar with Maven](https://stackoverflow.com/questions/1729054/including-dependencies-in-a-jar-with-maven).
- [Is it possible to build a java project only once using eclipse and share?
](https://stackoverflow.com/questions/35217128/is-it-possible-to-build-a-java-project-only-once-using-eclipse-and-share)

**Comment by Gu-Youngfeng** [comment]
The question is other 6 projects can be packaged with dependencies using maven-assembly-plugin, but only `Ormlite-Core` CANNOT.
