### ISSUE TITLE
Analyzing the access$XXX method in spoon

### ISSUE THREAD

**Issue by Gu-Youngfeng** [Gu-Youngfeng/EffciencyMinner#7]
Considering the follow frame in stack trace, how to analyze the **access$300** in TreeList ?

```java
java.lang.NullPointerException: null
	at org.apache.commons.collections4.list.TreeList$AVLNode.access$300(TreeList.java:305)
	at org.apache.commons.collections4.list.TreeList.addAll(TreeList.java:229)
```

Here is the partial code in `TreeList` class,

```java
...
public class TreeList<E> extends AbstractList<E> { /***  LINE 58  ***/
   ...
    static class AVLNode<E> {  /***  LINE 305  ***/
        /** The left child node or the predecessor if {@link #leftIsPrevious}.*/
        private AVLNode<E> left;
        /** Flag indicating that left reference is not a subtree but the predecessor. */
        private boolean leftIsPrevious;
    ...
}
```

**Comment by Gu-Youngfeng** [comment]
Actually, In `CLSAnalyzer` we only focus on mining features on the outer class (e.g.,`TreeList`) and ignore the inner class (e.g., `AVLNode`). The related code in `CrashNode`, `CLSAnalyzer`, and `MEDAnalyzer` should be updated.
