### ISSUE TITLE
Inconsistency between stack trace line and source project in JSqlParser

### ISSUE THREAD

**Issue by Gu-Youngfeng** [Gu-Youngfeng/EffciencyMinner#8]
When analyzing features in project, we find that some specific lines in stack trace are not in source project code, for example, considering the following stack trace.

```java
net.sf.jsqlparser.JSQLParserException: null
    at java.lang.System.arraycopy(Native Method)
    at net.sf.jsqlparser.parser.SimpleNode.jjtAddChild(SimpleNode.java:39)
    ...
```

and the class `SimpleNode` is as follows, and we can clearly see that function `jjtAddChild()` is between line 55 and line 64, but the stack trace says that the exception point is at line 39 in `jjtAddChild()`, it sounds weird, isn't it?

```java
/*
 * #%L
 * JSQLParser library
 * %%
 * Copyright (C) 2004 - 2017 JSQLParser
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 2.1 of the
 * License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Lesser Public License for more details.
 * 
 * You should have received a copy of the GNU General Lesser Public
 * License along with this program.  If not, see
 * <http://www.gnu.org/licenses/lgpl-2.1.html>.
 * #L%
 */
/* Generated By:JJTree: Do not edit this line. SimpleNode.java Version 6.1 */
/* JavaCCOptions:MULTI=false,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,
NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package net.sf.jsqlparser.parser;

public
class SimpleNode implements Node {  /*** Line 27 ***/
  ...
  public void jjtAddChild(Node n, int i) { /*** Line 55 ***/
    if (children == null) {
      children = new Node[i + 1];
    } else if (i >= children.length) {
      Node c[] = new Node[i + 1];
      System.arraycopy(children, 0, c, 0, children.length);
      children = c;
    }
    children[i] = n;
  }  /*** Line 64 ***/
  ...
}
```

**Comment by Gu-Youngfeng** [comment]
It seems that all these faults reside in project **JSqlParser**, which uses comment generation techniques during the compilation. Hence, the line number before and after compilation should have some inconsistencies. The other inconsistent stack traces include,

```java
at net.sf.jsqlparser.parser.CCJSqlParserDefaultVisitor.visit(CCJSqlParserDefaultVisitor.java:10)
```
```java
at net.sf.jsqlparser.parser.SimpleNode.childrenAccept(SimpleNode.java:72)
```
```java
at net.sf.jsqlparser.parser.JJTCCJSqlParserState.popNode(JJTCCJSqlParserState:57)
```

Above all, I suggest that we should modify the source code the same with the byte code, i.e., deleting the generated comments in such java file.

**Comment by Gu-Youngfeng** [comment]
Besides the above 3 kinds of conditions, there is still another interesting exception line in `InsertModifierPriority`,

```java
net.sf.jsqlparser.JSQLParserException: null
    at java.lang.Enum.valueOf(Enum.java:238)
    at net.sf.jsqlparser.statement.insert.InsertModifierPriority.valueOf(InsertModifierPriority.java:28)
	...
```

```java
package net.sf.jsqlparser.statement.insert;
...
public enum InsertModifierPriority {  /*** Line 28 ***/
    LOW_PRIORITY, DELAYED, HIGH_PRIORITY, IGNORE
}
```
